const ADD_MOVIES = "ADD_MOVIES";
const EDIT_MOVIES = "EDIT_MOVIES";
const DELETE_MOVIES = "DELETE_MOVIES";
const SEE_DETAIL = "SEE_DETAIL";

export { ADD_MOVIES, EDIT_MOVIES, DELETE_MOVIES, SEE_DETAIL };
